name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: bash ./buildAllPlatforms.sh


      - name: Install hub
        uses: geertvdc/setup-hub@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: bin/*

      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="build-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="Auto-Build $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create  -t "$GITHUB_SHA" "$tag" -m "$message" \
            $(for a in build/*.bin; do echo -a $a; done) 
        env:
          GITHUB_TOKEN: ${{ github.token }}
